### ISSUE TITLE
There's a Trojan agent inside the .exe file

### ISSUE THREAD

**Issue by AgentRG** [aljen/swtor_fix#9]
Like the title says. Malwarebytes, Kaspersky and Mac's own OS picked up a Trojan inside the .exe file.

**Comment by aljen** [comment]
Thanks for reporting that, but it's false positive :)

This exe should be used only on WINE, not on real Windows machines.
The reason it's reported as trojan is because to need what needs to be done, I'm modifying memory of other process, hence this error :)

If you want to confirm what I just said, compile it yourself and scan again :)
